services:
  wdv442-mysql:
    image: mysql:8.0
    restart: always
    networks: 
      - wdv442
    volumes:
      - ./var:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USER: asl
      MYSQL_PASSWORD: asl
      MYSQL_DATABASE: wdv442_space_tracker
    ports:
      - "3306:3306"
  wdv442-node:
    image: node:latest
    user: node
    working_dir: /home/node/app
    networks:
      - wdv442
    environment:
      - NODE_ENV=development
    volumes:
      - ./:/home/node/app
    ports:
      - "3001:3001"
    command: >
      sh -c "rm -rf node_modules &&
             npm install &&
             npm run watch"
    restart: always
    stdin_open: true
    tty: true
    depends_on:
      - wdv442-mysql
networks:
  wdv442:

