services:
  wdv442-mysql:
    image: mysql:8.0
    restart: always
    networks:
      wdv442:
        ipv4_address: 172.18.0.2
    volumes:
      - ./var:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USER: asl
      MYSQL_PASSWORD: asl
      MYSQL_DATABASE: wdv442_space_tracker
    ports:
      - "3306:3306"
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      timeout: 20s
      retries: 10
  wdv442-node:
    image: node:latest
    user: node
    working_dir: /home/node/app
    networks:
      wdv442:
        ipv4_address: 172.18.0.3
    environment:
      - NODE_ENV=development
      - DATABASE_HOST=localhost
    volumes:
      - ./:/home/node/app
    ports:
      - "3000:3000"
    command: >
      sh -c "rm -rf node_modules &&
             npm install &&
             npm run watch"
    restart: always
    stdin_open: true
    tty: true
    depends_on:
      - wdv442-mysql
networks:
  wdv442:
    ipam:
      config:
        - subnet: 172.18.0.0/16